localhost->remote:ssh
remote->localhost:http

remote->localhost:req
localhost->remote:resp

localhost->backend:req
backend->localhost:resp

browser->remote:req
browser<-remote:resp

browser->localhost:req
browser<-localhost:resp

browser->backend:req
browser<-backend:resp


remote.shape:cloud
