ssh隧道:{
    localhost->remote:ssh登录
    remote->localhost:ssh隧道
    remote.shape:cloud
}

直接访问:{
    browser->backend:req
    browser<-backend:resp
}

本地代理:{
    browser->localhost:req
    browser<-localhost:resp
    localhost->backend:req
    backend->localhost:resp
}

外网代理:{
    browser->remote:req
    browser<-remote:resp
    remote->localhost:req
    localhost->remote:resp
    localhost->backend:req
    backend->localhost:resp


    remote.shape:cloud
}









