shape: sequence_diagram

backend_server
local_server
ssh_server
other_server

启动阶段: {
    local_server->ssh_server:ssh_login
    local_server<-ssh_server:ssh 登录成功
    local_server->ssh_server:sftp_copy 辅助转发服务器
    local_server->ssh_server:ssh  启动转发服务器
}

启动成功运行阶段:{

        other_server->ssh_server.a:请求udp packet{
            style.animated: true
            style.stroke: red
        }
    
        ssh_server.a->local_server.a:udp forward 发送给 udp client {
            style.animated: true
            style.stroke: red
        }
 
        local_server.a->backend_server.a: "udp 转发给 udp server"{
            style.animated: true
            style.stroke: red
        }

        backend_server.b->local_server.b:发送ok字符串给 udp的请求端{
            style.animated: true
            style.stroke: green
        } 

        ssh_server.b<-local_server.b: 发送给 ssh 所在的 udp forawrd {
            style.animated: true
            style.stroke: green
        }
      
        other_server<-ssh_server.b:返回udp 请求回复{
            style.animated: true
            style.stroke:green
        }
        other_server.一次交互完成

}
