[proxy.Local4]
Name = "Local4"
Desc = "ssh 使用密码认证测试"
# 是否开启代理
Enable = true   
Url = "http://123.249.115.24:8081"
Proxy = "http://127.0.0.1:8088/api/v2.0.0"
Root = "./static/"
[proxy.Local4.ssh]
Auth = "password"
Password = "xxxxxx"
Host = "123.249.115.24:22"
# 是否开启代理
Enable = true   
UserName = "root"
PrivateKey = "./key/id_rsa"
Addr = "http://0.0.0.0:8081"